fixes:
  - "ballerina/log/*/::log-ballerina/"
  - "io/ballerina/stdlib/log/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/"

ignore:
  - "**/tests"
  - "test-utils"
  - "compiler-plugin"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
