[package]
org = "ballerina"
name = "integration_tests"
version = "@toml.version@"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-native"
path = "../native/build/libs/log-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "log-test-utils"
scope = "testOnly"
path = "../test-utils/build/libs/log-test-utils-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "./lib/io-native-@io.native.version@.jar"
